/*====================================================================================================================
 * File:
 *   passphrase.component.ts
 *
 * Comments:
 *   This component subscribes to "PeerMessageService" in order to receive the word generated by the dice component.
 *   It then combines those words and presents them to the user. It does not modify the current message from the
 *   peer service.
 *
 *====================================================================================================================*/
import {Component, OnInit } from '@angular/core';
import { PeerMessageService } from '../peer-message.service'

@Component({
  selector: 'app-passphrase',
  templateUrl: './passphrase.component.html',
  styleUrls: ['./passphrase.component.css'],
})
export class PassphraseComponent implements OnInit {
  title: string = "Make Passphrase";
  currentPassphrase: string = "";
  combinedPassphrase: string = "";

  //Service dependency injection to peer message services
  constructor(private peerMessageService: PeerMessageService) { }


  //Subscribes to data service when the component is initialized setting it to the components currentPassphrase
  ngOnInit() {
    this.peerMessageService.currentMessage.subscribe(message => this.currentPassphrase = message)
  }

  savePhrase(){
    if(this.currentPassphrase != ""){
      this.combinedPassphrase = this.combinedPassphrase.concat(" " + this.currentPassphrase);
    }
  }

  clear(){
    this.currentPassphrase = "";
    this.combinedPassphrase = "";
  }
}
